## Hyperparameter Tuning

Hyperparameter tuning is the process of finding the optimal set of hyperparameters for a machine learning model. Hyperparameters are external configuration variables whose values are set before the learning process begins (e.g., learning rate, number of trees in a Random Forest, `C` and `gamma` in SVM, `n_neighbors` in KNN).

**Why is it important?**
- **Model Performance:** Different hyperparameter values can significantly impact a model's performance, leading to better accuracy, precision, recall, or F1-score.
- **Prevent Overfitting/Underfitting:** Proper tuning helps in finding a balance that prevents the model from being too complex (overfitting) or too simple (underfitting).
- **Generalization:** An optimally tuned model generalizes better to unseen data.

**Common Techniques:**
- **Manual Search:** Adjusting hyperparameters based on experience and trial-and-error.
- **Grid Search:** Exhaustively searching through a predefined subset of the hyperparameter space.
- **Random Search:** Randomly sampling hyperparameters from a predefined distribution.
- **Bayesian Optimization:** Building a probabilistic model of the objective function to efficiently find the optimal hyperparameters.
- **Gradient-based Optimization:** Using gradients to update hyperparameters.

Techniques like `GridSearchCV` and `RandomizedSearchCV` (which you've used) automate this process by combining hyperparameter search with cross-validation to find the best-performing hyperparameters.

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = sns.load_dataset('titanic')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [ ]:
df['age'].fillna(df['age'].mean() , inplace = True)
df.drop('deck' , axis = 1 , inplace=True)
df.drop('alive' , axis = 1 , inplace = True)
df.drop(['who'] , axis = 1 , inplace=True)
df.drop('embark_town' , axis =1 , inplace = True)
df.drop('class' , axis = 1, inplace= True)
df.drop('adult_male' , axis = 1 , inplace=True)
df.dropna(subset = ['embarked'] , inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  889 non-null    int64  
 1   pclass    889 non-null    int64  
 2   sex       889 non-null    object 
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64  
 5   parch     889 non-null    int64  
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     889 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB


In [ ]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,male,22.000000,1,0,7.2500,S,False
1,1,1,female,38.000000,1,0,71.2833,C,False
2,1,3,female,26.000000,0,0,7.9250,S,True
3,1,1,female,35.000000,1,0,53.1000,S,False
4,0,3,male,35.000000,0,0,8.0500,S,True
...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,True
887,1,1,female,19.000000,0,0,30.0000,S,True
888,0,3,female,29.699118,1,2,23.4500,S,False
889,1,1,male,26.000000,0,0,30.0000,C,True


In [ ]:
X = df.drop('survived' , axis= 1)
y = df['survived']

In [ ]:
X

,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,3,male,22.000000,1,0,7.2500,S,False
1,1,female,38.000000,1,0,71.2833,C,False
2,3,female,26.000000,0,0,7.9250,S,True
3,1,female,35.000000,1,0,53.1000,S,False
4,3,male,35.000000,0,0,8.0500,S,True
...,...,...,...,...,...,...,...,...
886,2,male,27.000000,0,0,13.0000,S,True
887,1,female,19.000000,0,0,30.0000,S,True
888,3,female,29.699118,1,2,23.4500,S,False
889,1,male,26.000000,0,0,30.0000,C,True


In [ ]:
X_level= X.copy()

In [ ]:
#level_encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
X_level['sex'] = le.fit_transform(X_level['sex'])
X_level['embarked'] = le.fit_transform(X_level['embarked'])
X_level['alone'] = le.fit_transform(X_level['alone'])


In [ ]:
X_level.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   pclass    889 non-null    int64  
 1   sex       889 non-null    int64  
 2   age       889 non-null    float64
 3   sibsp     889 non-null    int64  
 4   parch     889 non-null    int64  
 5   fare      889 non-null    float64
 6   embarked  889 non-null    int64  
 7   alone     889 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 62.5 KB


In [ ]:
#level_encoding
#from sklearn.preprocessing import LabelEncoder

#le = LabelEncoder()

#for col in X_level.select_dtypes(include=['object','bool','category']).columns:
    #X_level[col] = le.fit_transform(X_level[col])

In [ ]:
X_level

,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,3,1,22.000000,1,0,7.2500,2,0
1,1,0,38.000000,1,0,71.2833,0,0
2,3,0,26.000000,0,0,7.9250,2,1
3,1,0,35.000000,1,0,53.1000,2,0
4,3,1,35.000000,0,0,8.0500,2,1
...,...,...,...,...,...,...,...,...
886,2,1,27.000000,0,0,13.0000,2,1
887,1,0,19.000000,0,0,30.0000,2,1
888,3,0,29.699118,1,2,23.4500,2,0
889,1,1,26.000000,0,0,30.0000,0,1


In [ ]:
#standered scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaler = scaler.fit_transform(X_level)

In [ ]:
X_level

,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,3,1,22.000000,1,0,7.2500,2,0
1,1,0,38.000000,1,0,71.2833,0,0
2,3,0,26.000000,0,0,7.9250,2,1
3,1,0,35.000000,1,0,53.1000,2,0
4,3,1,35.000000,0,0,8.0500,2,1
...,...,...,...,...,...,...,...,...
886,2,1,27.000000,0,0,13.0000,2,1
887,1,0,19.000000,0,0,30.0000,2,1
888,3,0,29.699118,1,2,23.4500,2,0
889,1,1,26.000000,0,0,30.0000,0,1


In [ ]:
X_scaler_df = pd.DataFrame(X_scaler, columns=X_level.columns, index=X_level.index)
display(X_scaler_df.head())

,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0.825209,0.735342,-0.590495,0.431350,-0.474326,-0.500240,0.586840,-1.229349
1,-1.572211,-1.359911,0.643971,0.431350,-0.474326,0.788947,-1.939555,-1.229349
2,0.825209,-1.359911,-0.281878,-0.475199,-0.474326,-0.486650,0.586840,0.813439
3,-1.572211,-1.359911,0.412509,0.431350,-0.474326,0.422861,0.586840,-1.229349
4,0.825209,0.735342,0.412509,-0.475199,-0.474326,-0.484133,0.586840,0.813439


In [ ]:
X_scaler_df.info

<bound method DataFrame.info of        pclass       sex       age     sibsp     parch      fare  embarked  \
0    0.825209  0.735342 -0.590495  0.431350 -0.474326 -0.500240  0.586840   
1   -1.572211 -1.359911  0.643971  0.431350 -0.474326  0.788947 -1.939555   
2    0.825209 -1.359911 -0.281878 -0.475199 -0.474326 -0.486650  0.586840   
3   -1.572211 -1.359911  0.412509  0.431350 -0.474326  0.422861  0.586840   
4    0.825209  0.735342  0.412509 -0.475199 -0.474326 -0.484133  0.586840   
..        ...       ...       ...       ...       ...       ...       ...   
886 -0.373501  0.735342 -0.204724 -0.475199 -0.474326 -0.384475  0.586840   
887 -1.572211 -1.359911 -0.821957 -0.475199 -0.474326 -0.042213  0.586840   
888  0.825209 -1.359911  0.003524  0.431350  2.006119 -0.174084  0.586840   
889 -1.572211  0.735342 -0.281878 -0.475199 -0.474326 -0.042213 -1.939555   
890  0.825209  0.735342  0.181046 -0.475199 -0.474326 -0.490173 -0.676357   

        alone  
0   -1.229349  
1   -1.229349  
2    0.813439  
3   -1.229349  
4    0.813439  
..        ...  
886  0.813439  
887  0.813439  
888 -1.229349  
889  0.813439  
890  0.813439  

[889 rows x 8 columns]>

In [ ]:
#traintestsplit
from sklearn.model_selection import train_test_split
X_train_level , X_test_level , y_train , y_test = train_test_split(X_level , y , test_size=0.2 , random_state=42)

In [ ]:
#traintestsplit
from sklearn.model_selection import train_test_split
X_train_scaler , X_test_scaler , y_train , y_test = train_test_split(X_scaler_df , y , test_size=0.2 , random_state=42)

In [ ]:
#logistic reg
from sklearn.linear_model import LogisticRegression
model_logistic_level = LogisticRegression()
model_logistic_level.fit(X_train_level , y_train)

LogisticRegression()

In [ ]:
y_pred_level_logistic = model_logistic_level.predict(X_test_level)

In [ ]:
model_logistic_scale = LogisticRegression()
model_logistic_scale.fit(X_train_scaler , y_train)

LogisticRegression()

In [ ]:
y_pred_scaler_logistic = model_logistic_scale.predict(X_test_scaler)

In [ ]:
# accuracy , confution matrics , classification report
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report

In [ ]:
accuracy_score(y_test , y_pred_level_logistic)

0.8033707865168539

In [ ]:
level_acc_logistic = accuracy_score(y_test , y_pred_level_logistic)
confusion_level_logistic = confusion_matrix(y_test , y_pred_level_logistic)
classification_report_logistic_level = classification_report(y_test , y_pred_level_logistic)

In [ ]:
print(level_acc_logistic)
print(confusion_level_logistic)
print(classification_report_logistic_level)

0.8033707865168539
[[90 19]
 [16 53]]
              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178



In [ ]:
scale_acc_logistic = accuracy_score(y_test , y_pred_scaler_logistic)
confusion_scale_logistic = confusion_matrix(y_test , y_pred_scaler_logistic)
classification_report_logistic_scale = classification_report(y_test , y_pred_scaler_logistic)

In [ ]:
print(scale_acc_logistic)
print(confusion_scale_logistic)
print(classification_report_logistic_scale)

0.8033707865168539
[[90 19]
 [16 53]]
              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178



In [ ]:
#KNN
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
model_knn_scaler = KNeighborsClassifier(n_neighbors = 5, weights = 'distance')
model_knn_scaler.fit(X_train_scaler , y_train)

KNeighborsClassifier(weights='distance')

In [ ]:
y_pred_scaler_knn = model_knn_scaler.predict(X_test_scaler)

In [ ]:
accuracy_score(y_test , y_pred_scaler_knn)

0.7921348314606742

In [ ]:
# naive bais
from sklearn.naive_bayes import GaussianNB
model_nb_level = GaussianNB()
model_nb_level.fit(X_train_level , y_train)

GaussianNB()

In [ ]:
y_pred_level_nb= model_nb_level.predict(X_test_level)

In [ ]:
accuracy_score(y_test , y_pred_level_nb)

0.7752808988764045

In [ ]:
acc_nb = accuracy_score(y_test , y_pred_level_nb)
confusion_nb = confusion_matrix(y_test , y_pred_level_nb)
classification_rep_nb = classification_report(y_test , y_pred_level_nb)

In [ ]:
print(acc_nb)
print(confusion_nb)
print(classification_rep_nb)

0.7752808988764045
[[84 25]
 [15 54]]
              precision    recall  f1-score   support

           0       0.85      0.77      0.81       109
           1       0.68      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.78      0.78      0.78       178



In [ ]:
#decesionTree
from sklearn.tree import DecisionTreeClassifier
model_dt = DecisionTreeClassifier()
model_dt.fit(X_train_scaler , y_train)

DecisionTreeClassifier()

In [ ]:
y_pred_dt = model_dt.predict(X_test_scaler)

In [ ]:
acc_dt = accuracy_score(y_test , y_pred_dt)
confusion_dt = confusion_matrix(y_test , y_pred_dt)
classification_rep_dt = classification_report(y_test , y_pred_dt)

In [ ]:
print(acc_dt)
print(confusion_dt)
print(classification_rep_dt)

0.7471910112359551
[[80 29]
 [16 53]]
              precision    recall  f1-score   support

           0       0.83      0.73      0.78       109
           1       0.65      0.77      0.70        69

    accuracy                           0.75       178
   macro avg       0.74      0.75      0.74       178
weighted avg       0.76      0.75      0.75       178



In [ ]:
# svm
from sklearn.svm import SVC
model_svm = SVC(kernel= 'rbf')
model_svm.fit(X_train_scaler , y_train)

SVC()

In [ ]:
y_pred_svm = model_svm.predict(X_test_scaler)
acc_svm = accuracy_score(y_test , y_pred_svm)
confusion_svm = confusion_matrix(y_test , y_pred_svm)
classification_rep_svm = classification_report(y_test , y_pred_svm)

print(acc_svm)
print(confusion_svm)
print(classification_rep_svm)

0.8146067415730337
[[91 18]
 [15 54]]
              precision    recall  f1-score   support

           0       0.86      0.83      0.85       109
           1       0.75      0.78      0.77        69

    accuracy                           0.81       178
   macro avg       0.80      0.81      0.81       178
weighted avg       0.82      0.81      0.82       178



In [ ]:
# cross validation
from sklearn.model_selection import cross_val_score
score = cross_val_score(model_svm , X_scaler_df , y , cv = 5 , scoring = 'accuracy')
score

array([0.83146067, 0.82022472, 0.81460674, 0.80898876, 0.86440678])

In [ ]:
print(score.mean())

0.8279375357074844


In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'C': [0.1, 1, 10, 100],
    'gamma': [1, 0.1, 0.01, 0.001],
    'kernel': ['rbf', 'linear', 'poly', 'sigmoid']
}

classifier = GridSearchCV(SVC(), param_grid, refit=True, verbose=2, cv=5)
classifier.fit(X_train_scaler, y_train)

Fitting 5 folds for each of 64 candidates, totalling 320 fits
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.1, gamma=1, kernel=linear; total time=   0.0s
[CV] END ......................C=0.1, gamma=1, kernel=linear; total time=   0.0s
[CV] END ......................C=0.1, gamma=1, kernel=linear; total time=   0.0s
[CV] END ......................C=0.1, gamma=1, kernel=linear; total time=   0.0s
[CV] END ......................C=0.1, gamma=1, kernel=linear; total time=   0.0s
[CV] END ........................C=0.1, gamma=1, kernel=poly; total time=   0.1s
[CV] END ........................C=0.1, gamma=1

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100], 'gamma': [1, 0.1, 0.01, 0.001],
                         'kernel': ['rbf', 'linear', 'poly', 'sigmoid']},
             verbose=2)

### Grid Search Cross-Validation

Grid Search Cross-Validation (GridSearchCV) is a technique used for hyperparameter tuning. It exhaustively searches through a specified subset of hyperparameters, evaluating a model for each combination of hyperparameter values using cross-validation.

**Key steps:**
1. **Define parameter grid:** Specify a dictionary where keys are the hyperparameters of the model and values are the lists of settings to try for each hyperparameter.
2. **Initialize GridSearchCV:** Pass the model, the parameter grid, and cross-validation details (e.g., `cv=5` for 5-fold cross-validation).
3. **Fit the grid search:** Call the `fit` method on your training data. GridSearchCV will then train the model for every combination of hyperparameters in the grid, using cross-validation to evaluate performance.
4. **Get the best estimator:** After fitting, you can access the best model (`best_estimator_`) and its corresponding hyperparameters (`best_params_`) and score (`best_score_`).

In [ ]:
accuracy_score(y_test , classifier.predict(X_test_scaler))

0.8202247191011236

In [ ]:
#random_search_cv
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

random_classifier = RandomizedSearchCV(SVC(), param_distributions=param_grid, n_iter=10, cv=5, random_state=42)
random_classifier.fit(X_train_scaler, y_train)

RandomizedSearchCV(cv=5, estimator=SVC(),
                   param_distributions={'C': [0.1, 1, 10, 100],
                                        'gamma': [1, 0.1, 0.01, 0.001],
                                        'kernel': ['rbf', 'linear', 'poly',
                                                   'sigmoid']},
                   random_state=42)

### Randomized Search Cross-Validation

Randomized Search Cross-Validation (`RandomizedSearchCV`) is a hyperparameter tuning technique that samples a fixed number of hyperparameter settings from a specified distribution. This approach can be more computationally efficient than `GridSearchCV`, especially when dealing with a large hyperparameter space, as it doesn't try every single combination.

**Key steps:**
1. **Define parameter distribution:** Specify a dictionary where keys are the hyperparameters of the model and values are either distributions (e.g., from `scipy.stats`) or lists of settings to randomly sample from for each hyperparameter.
2. **Initialize RandomizedSearchCV:** Pass the model, the parameter distributions, the number of iterations (`n_iter`) (which is the number of parameter settings that are sampled), and cross-validation details (e.g., `cv=5`). You can also set a `random_state` for reproducibility.
3. **Fit the random search:** Call the `fit` method on your training data. `RandomizedSearchCV` will randomly select `n_iter` combinations of hyperparameters from the defined distributions and train the model for each, using cross-validation to evaluate performance.
4. **Get the best estimator:** After fitting, you can access the best model (`best_estimator_`) and its corresponding hyperparameters (`best_params_`) and score (`best_score_`).

In [ ]:
accuracy_score(y_test , random_classifier.predict(X_test_scaler))

0.7752808988764045